service: mercredistes-scraper
frameworkVersion: ">=2.0.0 <3.0.0"
variablesResolutionMode: 20210326

custom:
  stage: ${file(stages/${opt:stage, self:provider.stage}.yml)}
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

plugins:
  - serverless-webpack

package:
  individually: true

provider:
  name: aws
  lambdaHashingVersion: 20201221
  runtime: nodejs14.x
  logRetentionInDays: ${self:custom.stage.lambda.logRetention}
  httpApi:
    useProviderTags: true
  stage: dev
  region: ${opt:region, self:custom.stage.region}
  profile: ${self:custom.stage.profile}
  iamRoleStatements: ${file(config/iamRoleStatements.yml)}
  deploymentBucket:
    name: com.serverless.${self:custom.stage.profile}.${self:provider.region}.deploys
    tags:
      Name: mercredistes-scraper
      billing_entity: daniel
      role: content
      project: mercredistes.mesphotos.ch
      service: deployment
  stackTags:
    Name: mercredistes-scraper
    billing_entity: daniel
    role: content
    project: mercredistes.mesphotos.ch
    service: stack

functions: ${file(lib/config.js):functions}
# resources:
#   Resources: ${file(lib/config.js):resources}
#   Outputs: ${file(lib/config.js):outputs}
