profile: mesphotos
region: eu-central-1
extension: ""
## Add any additional stage related variables. You can re-use the definition in serverless.yml:custom
# customStageVar: customStageValue
## Default Lambda related configs. Can be overwritten in each function
lambda:
  memorySize: 2048
  timeout: 900
  logRetention: 14
